# Generated by Django 4.0.1 on 2022-01-14 09:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('opensea', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='collection',
            name='average_price',
        ),
        migrations.RemoveField(
            model_name='collection',
            name='count',
        ),
        migrations.RemoveField(
            model_name='collection',
            name='floor_price',
        ),
        migrations.RemoveField(
            model_name='collection',
            name='market_cap',
        ),
        migrations.RemoveField(
            model_name='collection',
            name='num_owners',
        ),
        migrations.RemoveField(
            model_name='collection',
            name='num_reports',
        ),
        migrations.RemoveField(
            model_name='collection',
            name='one_day_average_price',
        ),
        migrations.RemoveField(
            model_name='collection',
            name='one_day_change',
        ),
        migrations.RemoveField(
            model_name='collection',
            name='one_day_sales',
        ),
        migrations.RemoveField(
            model_name='collection',
            name='one_day_volume',
        ),
        migrations.RemoveField(
            model_name='collection',
            name='seven_day_average_price',
        ),
        migrations.RemoveField(
            model_name='collection',
            name='seven_day_change',
        ),
        migrations.RemoveField(
            model_name='collection',
            name='seven_day_sales',
        ),
        migrations.RemoveField(
            model_name='collection',
            name='seven_day_volume',
        ),
        migrations.RemoveField(
            model_name='collection',
            name='thirty_day_average_price',
        ),
        migrations.RemoveField(
            model_name='collection',
            name='thirty_day_change',
        ),
        migrations.RemoveField(
            model_name='collection',
            name='thirty_day_sales',
        ),
        migrations.RemoveField(
            model_name='collection',
            name='thirty_day_volume',
        ),
        migrations.RemoveField(
            model_name='collection',
            name='total_sales',
        ),
        migrations.RemoveField(
            model_name='collection',
            name='total_supply',
        ),
        migrations.RemoveField(
            model_name='collection',
            name='total_volume',
        ),
        migrations.CreateModel(
            name='CollectionStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('one_day_volume', models.FloatField(blank=True, default=0.0)),
                ('one_day_change', models.FloatField(blank=True, default=0.0)),
                ('one_day_sales', models.FloatField(blank=True, default=0.0)),
                ('one_day_average_price', models.FloatField(blank=True, default=0.0)),
                ('seven_day_volume', models.FloatField(blank=True, default=0.0)),
                ('seven_day_change', models.FloatField(blank=True, default=0.0)),
                ('seven_day_sales', models.FloatField(blank=True, default=0.0)),
                ('seven_day_average_price', models.FloatField(blank=True, default=0.0)),
                ('thirty_day_volume', models.FloatField(blank=True, default=0.0)),
                ('thirty_day_change', models.FloatField(blank=True, default=0.0)),
                ('thirty_day_sales', models.FloatField(blank=True, default=0.0)),
                ('thirty_day_average_price', models.FloatField(blank=True, default=0.0)),
                ('total_volume', models.FloatField(blank=True, default=0.0)),
                ('total_sales', models.FloatField(blank=True, default=0.0)),
                ('total_supply', models.FloatField(blank=True, default=0.0)),
                ('count', models.FloatField(blank=True, default=0.0)),
                ('num_owners', models.FloatField(blank=True, default=0.0)),
                ('average_price', models.FloatField(blank=True, default=0.0)),
                ('num_reports', models.FloatField(blank=True, default=0.0)),
                ('market_cap', models.FloatField(blank=True, default=0.0)),
                ('floor_price', models.FloatField(blank=True, default=0.0)),
                ('collection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='opensea.collection')),
            ],
            options={
                'verbose_name': 'Collection stats',
                'verbose_name_plural': 'Collections stats',
            },
        ),
    ]
