# Generated by Django 4.0.1 on 2022-01-14 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('opensea', '0003_collectionstats_created'),
    ]

    operations = [
        migrations.AddField(
            model_name='collection',
            name='address',
            field=models.CharField(default='asdfasdf', max_length=50),
            preserve_default=False,
        ),
    ]
