# Generated by Django 4.0.1 on 2022-01-14 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('opensea', '0005_collection_updated'),
    ]

    operations = [
        migrations.AddField(
            model_name='collection',
            name='tracked',
            field=models.BooleanField(default=False),
        ),
    ]
