# Generated by Django 3.2.11 on 2022-01-16 08:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('opensea', '0006_collection_tracked'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collectionstats',
            name='collection',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='opensea.collection'),
        ),
    ]
