# Generated by Django 3.2.11 on 2022-01-17 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('opensea', '0007_alter_collectionstats_collection'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collection',
            name='address',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
